### ISSUE TITLE
What does "gallery_satellite_usa_un" mean?

### ISSUE THREAD

**Issue by rosekc** [wtyhub/LPN#1]
https://github.com/wtyhub/LPN/blob/00c33994aa83a46fa60f7c3bcfe8b45443956c4c/test.py#L133

请问这个是否可以无视？

**Comment by wtyhub** [comment]
Yes. You can ignore it. "gallery_satellite _usa_un" means that the satellite images of CVUSA are added to the satellite-view gallery of Univeristy1652 as distractors of geo-localization.
是的，你可以忽视。"gallery_satellite _usa_un"指的是在University1652数据集的卫星图gallery中加入cvusa的卫星图，其中，cvusa的卫星图作为地理定位检索的干扰项。

**Comment by rosekc** [comment]
好的感谢解答
