### ISSUE TITLE
CVUSA training exception

### ISSUE THREAD

**Issue by Allen-lz** [wtyhub/LPN#2]
hi,Thanks for your work！ 
But when I was training CVUSA, the loss was always very large, and the accuracy rate was very low.
I have processed the dataset according to prepare_cvusa.py

-- Epoch 33/189
 -- ----------
-- train Loss: 122.1055 Satellite_Acc: 0.0339  Street_Acc: 0.0411

-- Training complete in 450m 17s

**Comment by wtyhub** [comment]
Don‘t worry. When the epoch is 80 and the learing rate becomes 0.1*lr, the accuracy will improve.

**Comment by Allen-lz** [comment]
Thank you for your prompt reply, it is indeed the case.
